services:
  - type: web
    name: dreamforge-emporium
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          name: dreamforge-db
          type: mysql
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: dreamforge
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        fromService:
          name: dreamforge-db
          type: mysql
          property: password

databases:
  - name: dreamforge-db
    plan: free
    databaseName: dreamforge
