services:
  - type: web
    name: dreamforge-emporium
    runtime: docker
    repo: https://github.com/weezdiggity/OGameX.git
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: dreamforge-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dreamforge-db
          property: port
      - key: DB_DATABASE
        value: dreamforge
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: your_actual_password_here  # You must manually set this or store it securely

databases:
  - name: dreamforge-db
    plan: free
    databaseName: dreamforge

