
services:
  - type: web
    name: dreamforge-emporium
    runtime: docker
    repo: https://github.com/weezdiggity/OGameX.git
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: dreamforge-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: dreamforge
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        fromDatabase:
          name: dreamforge-db
          property: password

databases:
  - name: dreamforge-db
    plan: free
    databaseName: dreamforge
