name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl, openssl
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Commit vendor directory
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add vendor
          git commit -m "Add vendor from GitHub Action" || echo "No changes to commit"
          git push
